name: workflow1
on: push
jobs: 
  Run-Job: 
    runs-on: ubuntu-latest
    steps:
    - name: get Code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm run test
    - name:  build
      run: npm run build
    - name: Preview
      run: npm run preview
    - name: deploy Code
      run: echo "deploying code" 
