name: workflow1
  on: [push,workflow]
  jobs: 
    Run-Job: 
    runs-on: ubuntu-latest
    steps: 
      - name: get Code
      usues: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint  
        run: npm run lint
      - name: Test
        run: npm run test
      - name:  build
        run: npm build
      - name: deploy Code
        run: echo "deploying code" 
